
--RIGHT SCREEN 1-1. Diagnosis Patient Age & Gender Last 1 Year
DROP TABLE D02760.temp_condition_age ;
CREATE TABLE D02760.temp_condition_age AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
FROM FT_CRE_DGNS fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE 1=1
AND DGNS_REG_DT  BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND CLDG_VOC_ID IN (SELECT DISTINCT CLDG_VOC_ID FROM D02760.temp_condition_rank)
)
SELECT CLDG_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
, age_group
, SEX_TP_CD
,  count(DISTINCT PT_NO)  PCNT
FROM a 
	GROUP BY CLDG_VOC_ID,  age_group, sex_tp_cd
	ORDER BY 1, 2, 3, 4;


DROP TABLE D02760.temp_procedure_age ;
CREATE TABLE D02760.temp_procedure_age AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
FROM FT_CRE_SRGR fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE
SRGR_STR_DTM  BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND OP_VOC_ID IN (SELECT DISTINCT OP_VOC_ID FROM D02760.temp_procedure_rank)
)
SELECT OP_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
, age_group
, SEX_TP_CD
,  count(DISTINCT PT_NO) PCNT
FROM a 
	GROUP BY OP_VOC_ID,  age_group, sex_tp_cd
	ORDER BY 1, 2, 3, 4;


--RIGHT SCREEN 3-1. condition Visit by Location
DROP  TABLE D02760.temp_condition_SIDO;
CREATE TABLE D02760.temp_condition_SIDO AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY  BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY  BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY  BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY  BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY  BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY  BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY  BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY  BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY  BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY  BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
FROM FT_CRE_DGNS fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE 
DGNS_REG_DT BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND CLDG_VOC_ID IN (SELECT DISTINCT CLDG_VOC_ID FROM D02760.temp_condition_rank)
)
SELECT CLDG_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
, SIDO_ADDR
, count(DISTINCT PT_NO) PCNT
FROM a 
	GROUP BY CLDG_VOC_ID, SIDO_ADDR
	ORDER BY 1, 2, 4 DESC 
;


--RIGHT SCREEN 3-2. procedure Visit by Location
DROP  TABLE D02760.temp_procedure_SIDO;
CREATE TABLE D02760.temp_procedure_SIDO AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
FROM FT_CRE_SRGR fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE 1=1
AND SRGR_STR_DTM BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND OP_VOC_ID IN (SELECT DISTINCT OP_VOC_ID FROM D02760.temp_procedure_rank)
)
SELECT OP_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
, SIDO_ADDR
,  count(DISTINCT PT_NO)  PCNT
FROM a 
	GROUP BY OP_VOC_ID, SIDO_ADDR
	ORDER BY 1, 2, 4 DESC ;



--RIGHT SCREEN 4-1.  Visits by Department Last 1 Year
DROP TABLE D02760.temp_condition_DEPT;
CREATE TABLE D02760.temp_condition_DEPT AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
--to_char(DGNS_REG_DT, 'YYYY-MM'), count(DISTINCT PT_NO)
FROM FT_CRE_DGNS fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE 1=1
--AND CLDG_VOC_ID ='D00001437'
AND DGNS_REG_DT  BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND CLDG_VOC_ID IN (SELECT DISTINCT CLDG_VOC_ID FROM D02760.temp_condition_rank)
--GROUP BY to_char(DGNS_REG_DT, 'YYYY-MM')
)
--SELECT *
SELECT CLDG_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
, MED_DEPT_CD
, lsd.DEPT_NM MED_DEPT_NM
, count(DISTINCT PT_NO)  PCNT
FROM a a
LEFT JOIN LT_CRE_DEPT lsd
ON a.med_dept_cd= lsd.dept_cd
	GROUP BY CLDG_VOC_ID,  MED_DEPT_CD, lsd.DEPT_NM 
ORDER BY 1, 2, 5 DESC 
;


--RIGHT SCREEN 4-2.  Visits by Department Last 1 Year
DROP TABLE D02760.temp_procedure_DEPT ;
CREATE TABLE D02760.temp_procedure_DEPT AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD  , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
--to_char(DGNS_REG_DT, 'YYYY-MM'), count(DISTINCT PT_NO)
FROM FT_CRE_SRGR fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE 1=1
--AND CLDG_VOC_ID ='D00001437'
AND SRGR_STR_DTM  BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND OP_VOC_ID IN (SELECT DISTINCT OP_VOC_ID FROM D02760.temp_procedure_rank)
--GROUP BY to_char(DGNS_REG_DT, 'YYYY-MM')
)
--SELECT MED_DEPT_CD , MED_DEPT_NM 
SELECT OP_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
, MED_DEPT_CD 
, lsd.DEPT_NM MED_DEPT_NM
, count(DISTINCT PT_NO)   PCNT
FROM a a
LEFT JOIN LT_CRE_DEPT lsd
ON a.med_dept_cd= lsd.dept_cd
	GROUP BY OP_VOC_ID, MED_DEPT_CD , lsd.DEPT_NM 
	ORDER BY 1, 2, 5 desc
;


--RIGHT SCREEN 2-1.  Patient Monthly Visits
DROP TABLE D02760.temp_condition_MONTHLY;
CREATE TABLE D02760.temp_condition_MONTHLY AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
FROM FT_CRE_DGNS fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE 1=1
AND DGNS_REG_DT  BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND CLDG_VOC_ID IN (SELECT DISTINCT CLDG_VOC_ID FROM D02760.temp_condition_rank)
)
SELECT CLDG_VOC_ID "VOC_ID", TO_CHAR(DGNS_REG_DT, 'YYYY-MM') "DATE"
, count(DISTINCT PT_NO)  PCNT
FROM a 
	GROUP BY CLDG_VOC_ID, TO_CHAR(DGNS_REG_DT, 'YYYY-MM')
	ORDER BY 1, 2, 3 DESC 
;


--RIGHT SCREEN 2-2.  Patient Monthly Visits
DROP TABLE D02760.temp_procedure_MONTHLY;
CREATE TABLE D02760.temp_procedure_MONTHLY AS 
WITH a AS (
SELECT  fsd.*, lsp.SIDO_ADDR, lsp.SEX_TP_CD , lsp.AGE_CD_YY 
, CASE WHEN  lsp.AGE_CD_YY BETWEEN 0 AND 10 THEN '0 - 10'
WHEN lsp.AGE_CD_YY BETWEEN 11 AND 20 THEN '11 - 20'
WHEN lsp.AGE_CD_YY BETWEEN 21 AND 30 THEN '21 - 30'
WHEN lsp.AGE_CD_YY BETWEEN 31 AND 40 THEN '31 - 40'
WHEN lsp.AGE_CD_YY BETWEEN 41 AND 50 THEN '41 - 50'
WHEN lsp.AGE_CD_YY BETWEEN 51 AND 60 THEN '51 - 60'
WHEN lsp.AGE_CD_YY BETWEEN 61 AND 70 THEN '61 - 70'
WHEN lsp.AGE_CD_YY BETWEEN 71 AND 80 THEN '71 - 80'
WHEN lsp.AGE_CD_YY BETWEEN 81 AND 90 THEN '81 - 90'
WHEN lsp.AGE_CD_YY BETWEEN 91 AND 100 THEN '91 - 100'
ELSE 'OVER 100' END AGE_GROUP
FROM FT_CRE_SRGR fsd 
LEFT JOIN LT_CRE_PT lsp
ON fsd.PT_NO = lsp.PT_NO 
WHERE 1=1
AND SRGR_STR_DTM BETWEEN date_trunc('month', now() - interval '1 year') 
AND date_trunc('month', now())::date - 1
AND OP_VOC_ID IN (SELECT DISTINCT OP_VOC_ID FROM D02760.temp_procedure_rank)
)
SELECT OP_VOC_ID "VOC_ID",  TO_CHAR(SRGR_STR_DTM, 'YYYY-MM') "DATE"
, count(DISTINCT PT_NO)   PCNT
FROM a 
	GROUP BY OP_VOC_ID, TO_CHAR(SRGR_STR_DTM, 'YYYY-MM')
	ORDER BY 1, 2, 3 DESC
;


--RIGHT SCREEN 5-1. top Lab data
DROP TABLE D02760.temp_condition_LAB ;
CREATE TABLE D02760.temp_condition_LAB AS 
WITH A AS (
	SELECT CLDG_VOC_ID, PACT_ID, PT_NO
	FROM FT_CRE_DGNS fcd
	WHERE DGNS_REG_DT  BETWEEN date_trunc('month', now() - interval '1 year') 
	AND date_trunc('month', now())::date - 1
	AND CLDG_VOC_ID IN (SELECT DISTINCT CLDG_VOC_ID FROM D02760.temp_condition_rank))
	, B AS (
	SELECT IMPL_DTM, PT_NO, EXM_CD, EXM_NM, PACT_ID
	FROM FT_CRE_EXM_LAB fs
	)
	, C AS (
	SELECT CLDG_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
		, EXM_CD
		, count(DISTINCT A.PT_NO)  PCNT
	FROM  A
	INNER JOIN B
	ON A.pact_id = B.PACT_ID 
	GROUP BY CLDG_VOC_ID
		, EXM_CD
		ORDER BY 1, 2, 4 DESC)
	select *
	, (SELECT  EXM_NM FROM LT_CRE_EXM b WHERE b.EXM_CD = C.EXM_CD) EXM_NM
	from C
	WHERE EXM_CD IS NOT NULL
;


--RIGHT SCREEN 5-2. top Lab data
DROP TABLE D02760.temp_procedure_LAB;
CREATE TABLE D02760.temp_procedure_LAB AS 
WITH A AS (
SELECT OP_VOC_ID "VOC_ID", date_part('year', now() - interval '1 month')::varchar "DATE"
, EXM_CD
, count(DISTINCT a.PT_NO)   PCNT
FROM (SELECT * FROM FT_CRE_SRGR fss WHERE SRGR_STR_DTM   BETWEEN date_trunc('month', now() - interval '1 year') 
	AND date_trunc('month', now())::date - 1
AND OP_VOC_ID IN (SELECT DISTINCT OP_VOC_ID FROM D02760.temp_procedure_rank)) a
INNER JOIN FT_CRE_EXM_LAB b
ON a.pact_id = b.PACT_ID 
	GROUP BY OP_VOC_ID
	, EXM_CD
	ORDER BY 1, 2, 4 DESC
	)
	SELECT *
	, (SELECT  EXM_NM FROM LT_CRE_EXM c WHERE A.EXM_CD= c.EXM_CD) EXM_NM
	FROM A
	WHERE EXM_CD IS NOT NULL
;
